name: Release artifact upload

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          # arm specific build
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: amd64
    env:
      OCAML_VERSION: "5.1.1"
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ†• Checkout
        uses: actions/checkout@v4

      - name: ğŸ« Set-up OCaml@${{ env.OCAML_VERSION }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ env.OCAML_VERSION }}
          dune-cache: true
          cache-prefix: ${{ env.OCAML_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}

      - name: ğŸ“¦ Install deps with opam
        run: opam install . --deps-only -y

      - name: ğŸœï¸ Build CLI bin with dune
        run: opam exec -- dune build --profile release bin

      - name: ğŸ“¤ Upload CLI bin
        uses: actions/upload-artifact@v4
        with:
          name: ddf-${{ env.OCAML_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ./_build/default/bin/ddf.exe
